### ISSUE TITLE
Latest update breaks DE's reactor redstone menu 

### ISSUE THREAD

**Issue by Aaron-Strong** [Draconic-Inc/BrandonsCore#99] opened 2022-06-29 21:22 UTC
Minecraft version: 1.16.5
Mod version: 3.0.14.248-universal
Minecraft Forge version: 36.2.33
Mod Pack: Oceanblock

When attempting to change the redstone output mode on a draconic reactor, nothing happens.
Here I am frantically clicking the menu praying it'll change modes:
 https://user-images.githubusercontent.com/11193236/176547005-3d04ccc1-5060-44f7-bba8-8af4e6727eea.mp4

Downgrading to the previous version of Brandon's Core resolves this issue, however, if a server is running the latest version the buttons remain bugged.

Steps to reproduce:
* Create a simple draconic reactor setup
* Charge the reactor
* Attempt to change the redstone mode

**Comment by brandon3055** [comment] 2022-06-30 07:08
This is caused by a recent change i made to packet security in BCore. It is now fixed. Just update DE.

**Closed by brandon3055** 2022-06-30 07:08 UTC
