### ISSUE TITLE
Brandon Core Crash

### ISSUE THREAD

**Issue by BlazeDracon** [Draconic-Inc/BrandonsCore#103] opened 2023-03-28 10:51 UTC
This is for the 1.18.2 version of Brandon's Core. After about 15 minutes of the loading screen for minecraft not responding the game will crash and a crash log with the error saying Brandon's Core (brandonscore) encountered an error during the done event phase§7java.lang.RuntimeException: Failed to initialize shader

**Comment by FoxMcloud5655** [comment] 2023-03-28 19:19
It sounds like you're running an older version of Brandon's Core.  However, the information you provided is sorely lacking.  What version of Brandon's Core?  Where is the full log?  What other mods did you have installed?  What version of CodeChickenLib did you have?

**Comment by BlazeDracon** [comment] 2023-03-31 00:03
I was trying to use the most recent version of both Brandon's Core and Code Chicken Lib for 1.18.2

**Comment by brandon3055** [comment] 2023-03-31 04:35
Please try this
https://maven.covers1624.net/com/brandon3055/brandonscore/BrandonsCore/1.18.2-3.1.9.281/BrandonsCore-1.18.2-3.1.9.281-universal.jar
If it still crashes, then please provide the new crash report.

**Comment by BlazeDracon** [comment] 2023-04-03 02:53
Thanks it worked

**Comment by FoxMcloud5655** [comment] 2023-04-03 06:39
Please close the issue since you've confirmed it works.

**Closed** 2023-04-03 22:01 UTC
